using Content.Shared._Functional.TutorialServer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Text;

namespace Content.Client._Functional.TutorialServer.UI;

[GenerateTypedNameReferences]
public sealed partial class TutorialPromptWindow : DefaultWindow
{
    public Action? OnNextPressed;
    public Action? OnHintPressed;

    public TutorialPromptWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("tutorial-server-prompt-title");

        NextButton.OnPressed += _ => OnNextPressed?.Invoke();
        HintButton.OnPressed += _ => OnHintPressed?.Invoke();
    }

    public void Populate(TutorialPromptBuiState state)
    {
        if (!state.HasTutorial)
        {
            SetLabel(GoalLabel, Loc.GetString("tutorial-server-prompt-no-tutorial"));
            ChecklistLabel.Visible = false;
            SetLabel(StepLabel, string.Empty);
            SetLabel(StatusLabel, string.Empty);
            NextButton.Disabled = true;
            HintButton.Disabled = true;
            HintButton.Visible = false;
            return;
        }

        if (state.GoalCount > 0)
        {
            SetLabel(GoalLabel, Loc.GetString("tutorial-server-goal-hud",
                ("current", state.ViewGoalIndex + 1),
                ("total", Math.Max(state.GoalCount, 1)),
                ("title", state.GoalTitle)));

            var sb = new StringBuilder();
            for (var i = 0; i < state.SubGoalStates.Count; i++)
            {
                var entry = state.SubGoalStates[i];
                var mark = entry.Completed
                    ? "[x]"
                    : i == state.ViewIndex
                        ? "[>]"
                        : i == state.ProgressIndex
                            ? "[*]"
                            : "[ ]";
                sb.AppendLine($"{mark} {entry.Text}");
            }

            SetLabel(ChecklistLabel, sb.ToString().TrimEnd());
            ChecklistLabel.Visible = state.SubGoalStates.Count > 0;
            SetLabel(StepLabel, Loc.GetString("tutorial-server-subgoal-hud",
                ("current", state.ViewIndex + 1),
                ("total", Math.Max(state.StepCount, 1)),
                ("text", state.StepText)));
        }
        else
        {
            SetLabel(GoalLabel, string.Empty);
            ChecklistLabel.Visible = false;
            SetLabel(StepLabel, Loc.GetString("tutorial-server-step-hud",
                ("current", state.ViewIndex + 1),
                ("total", Math.Max(state.StepCount, 1)),
                ("text", state.StepText)));
        }

        if (state.WaitingOnSensor)
        {
            SetLabel(StatusLabel, !string.IsNullOrEmpty(state.HintText)
                ? state.HintText
                : Loc.GetString("tutorial-server-prompt-waiting"));
        }
        else
        {
            SetLabel(StatusLabel, string.Empty);
        }

        NextButton.Disabled = !state.CanGoNext;
        NextButton.Text = state.ViewComplete == TutorialStepComplete.Acknowledge
            ? Loc.GetString("tutorial-server-acknowledge")
            : Loc.GetString("tutorial-server-prompt-next");

        var hasStuckHint = !string.IsNullOrEmpty(state.StuckHintText);
        HintButton.Visible = hasStuckHint;
        HintButton.Disabled = !hasStuckHint;
    }

    private static void SetLabel(Robust.Client.UserInterface.Controls.RichTextLabel label, string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            label.SetMessage(new FormattedMessage());
            return;
        }

        var msg = new FormattedMessage();
        msg.AddText(text);
        label.SetMessage(msg);
    }
}
