using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Functional.TutorialServer.StarlightSurgery;

/// <summary>
/// Simple choice row used by the tutorial Starlight surgery BUI (from Starlight / RMC-14).
/// </summary>
[GenerateTypedNameReferences]
[Virtual]
public partial class ChoiceControl : Control
{
    public ChoiceControl() => RobustXamlLoader.Load(this);

    public void Set(string name, Texture? texture)
    {
        NameLabel.SetMessage(name);
        Texture.Texture = texture;
    }

    public void Set(FormattedMessage msg, Texture? texture)
    {
        NameLabel.SetMessage(msg);
        Texture.Texture = texture;
    }
}
