- type: tutorialRole
  id: TutorialMedicalDoctor
  job: MedicalDoctor
  stub: false
  simplifiedEnvironment: true
  category: Medical
  map: /Maps/_Functional/TutorialServer/Roles/MedicalDoctor.yml
  roomTemplate: TutorialSectionMedbay
  guidebook: Medical
  practiceSpawns:
  - id: LockerMedicalFilled
    room: 0
    offset: -2, 1
  - id: HandheldHealthAnalyzer
    room: 0
    offset: 0.5, 0
  - id: TutorialVendingMachineMedical
    room: 0
    offset: 1.5, 1
  - id: TutorialPracticeMobPatient
    room: 0
    offset: 0, 0
  - id: Brutepack
    room: 0
    offset: 0.5, -1
  - id: Ointment
    room: 0
    offset: 0.8, -1
  - id: EmergencyMedipen
    room: 0
    offset: -0.5, -1
  - id: MedkitCombat
    room: 0
    offset: -0.8, -1
  - id: TutorialStepMarker
    room: 0
    offset: 0, -1.5
    marker: med-pass
  goals:
  - id: welcome
    title: tutorial-job-medical-doctor-goal-welcome
    subGoals:
    - id: intro
      text: tutorial-job-medical-doctor-sg-intro
      complete: Acknowledge
  - id: diagnose
    title: tutorial-job-medical-doctor-goal-diagnose
    subGoals:
    - id: hold-analyzer
      text: tutorial-job-medical-doctor-sg-analyzer
      complete: HoldItem
      entity: HandheldHealthAnalyzer
    - id: med-vend
      text: tutorial-job-medical-doctor-sg-vend
      complete: InteractTargetTag
      tag: TutorialVending
  - id: treat
    title: tutorial-job-medical-doctor-goal-treat
    subGoals:
    - id: get-brute
      text: tutorial-job-medical-doctor-sg-brutepack
      complete: ObtainItem
      entity: Brutepack
    - id: get-burn
      text: tutorial-job-medical-doctor-sg-ointment
      complete: ObtainItem
      entity: Ointment
    - id: heal-dummy
      text: tutorial-job-medical-doctor-sg-heal
      complete: PracticeMobDamageBelow
      maxDamage: 5
    - id: hold-epi
      text: tutorial-job-medical-doctor-sg-hold-epi
      complete: HoldItem
      entity: EmergencyMedipen
    - id: use-epi
      text: tutorial-job-medical-doctor-sg-use-epi
      complete: UseInHand
      entity: EmergencyMedipen
    - id: crit-tip
      text: tutorial-job-medical-doctor-sg-crit-tip
      complete: Acknowledge
    - id: walk
      text: tutorial-job-medical-doctor-sg-walk
      complete: ReachMarker
      marker: med-pass
  - id: finish
    title: tutorial-job-medical-doctor-goal-finish
    subGoals:
    - id: done
      text: tutorial-job-medical-doctor-sg-done
      complete: Acknowledge
