using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Guidebook;
using Content.Shared.Silicons.Borgs;
using Content.Shared.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Silicons.Borgs;

/// <summary>
/// Menu used by borgs to select their type.
/// </summary>
/// <seealso cref="BorgSelectTypeUserInterface"/>
/// <seealso cref="BorgSwitchableTypeComponent"/>
[GenerateTypedNameReferences]
public sealed partial class BorgSelectTypeMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private BorgTypePrototype? _selectedBorgType;

    public event Action<ProtoId<BorgTypePrototype>>? ConfirmedBorgType;

    private static readonly List<ProtoId<GuideEntryPrototype>> GuidebookEntries = new() { "Cyborgs", "Robotics" };

    public BorgSelectTypeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ConfirmTypeButton.OnPressed += ConfirmButtonPressed;
        HelpGuidebookIds = GuidebookEntries;
    }

    /// <summary>
    /// Rebuilds the type list. When <paramref name="available"/> is null or empty, every borg type is shown.
    /// </summary>
    public void Populate(IReadOnlyList<ProtoId<BorgTypePrototype>>? available)
    {
        SelectionsContainer.DisposeAllChildren();
        _selectedBorgType = null;
        InfoContents.Visible = false;
        InfoPlaceholder.Visible = true;
        ConfirmTypeButton.Disabled = true;

        var types = _prototypeManager.EnumeratePrototypes<BorgTypePrototype>().OrderBy(PrototypeName);
        if (available is { Count: > 0 })
        {
            var allowed = available.ToHashSet();
            types = types.Where(t => allowed.Contains(t.ID)).OrderBy(PrototypeName);
        }

        var group = new ButtonGroup();
        var count = 0;
        BorgTypePrototype? soleType = null;
        foreach (var borgType in types)
        {
            count++;
            soleType = borgType;
            var button = new Button
            {
                Text = PrototypeName(borgType),
                Group = group,
            };
            button.OnPressed += _ =>
            {
                _selectedBorgType = borgType;
                UpdateInformation(borgType);
            };
            SelectionsContainer.AddChild(button);
        }

        // Tutorial / constrained spawns often expose a single chassis — pre-select it.
        if (count == 1 && soleType != null)
            UpdateInformation(soleType);
    }

    private void UpdateInformation(BorgTypePrototype prototype)
    {
        _selectedBorgType = prototype;

        InfoContents.Visible = true;
        InfoPlaceholder.Visible = false;
        ConfirmTypeButton.Disabled = false;

        NameLabel.Text = PrototypeName(prototype);
        DescriptionLabel.Text = Loc.GetString($"borg-type-{prototype.ID}-desc");
        ChassisView.SetPrototype(prototype.DummyPrototype);
    }

    private void ConfirmButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedBorgType == null)
            return;

        ConfirmedBorgType?.Invoke(_selectedBorgType);
    }

    private static string PrototypeName(BorgTypePrototype prototype)
    {
        return Loc.GetString($"borg-type-{prototype.ID}-name");
    }
}
