using Content.Shared._Functional.TutorialServer.CyberMedSurgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Functional.TutorialServer.CyberMedSurgery;

[GenerateTypedNameReferences]
public sealed partial class TutorialCyberMedSurgeryWindow : DefaultWindow
{
    public Action<string>? OnPartSelected;
    public Action<TutorialCyberMedLayer>? OnLayerSelected;
    public Action<string>? OnStepSelected;

    public TutorialCyberMedSurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("tutorial-cybermed-window-title");

        SkinLayerButton.OnPressed += _ => OnLayerSelected?.Invoke(TutorialCyberMedLayer.Skin);
        TissueLayerButton.OnPressed += _ => OnLayerSelected?.Invoke(TutorialCyberMedLayer.Tissue);
        OrganLayerButton.OnPressed += _ => OnLayerSelected?.Invoke(TutorialCyberMedLayer.Organ);
    }

    public void Populate(TutorialCyberMedBuiState state)
    {
        var patientMsg = new FormattedMessage();
        patientMsg.AddText(Loc.GetString("tutorial-cybermed-patient-label", ("name", state.PatientName)));
        PatientLabel.SetMessage(patientMsg);

        PartButtons.DisposeAllChildren();
        foreach (var part in state.Parts)
        {
            var button = new Button
            {
                Text = part,
                ToggleMode = true,
                Pressed = part == state.SelectedPart,
            };
            var captured = part;
            button.OnPressed += _ => OnPartSelected?.Invoke(captured);
            PartButtons.AddChild(button);
        }

        SkinLayerButton.Pressed = state.SelectedLayer == TutorialCyberMedLayer.Skin;
        TissueLayerButton.Pressed = state.SelectedLayer == TutorialCyberMedLayer.Tissue;
        OrganLayerButton.Pressed = state.SelectedLayer == TutorialCyberMedLayer.Organ;

        StepsList.DisposeAllChildren();
        if (state.Steps.Count == 0)
        {
            var empty = new RichTextLabel { MaxWidth = 340, HorizontalExpand = true };
            var emptyMsg = new FormattedMessage();
            emptyMsg.AddText(Loc.GetString("tutorial-cybermed-no-steps"));
            empty.SetMessage(emptyMsg);
            StepsList.AddChild(empty);
            return;
        }

        foreach (var step in state.Steps)
        {
            var text = step.Completed
                ? $"{step.Name} ({step.ToolLabel}) ✓"
                : step.Available
                    ? $"{step.Name} ({step.ToolLabel})"
                    : $"{step.Name} ({step.ToolLabel}) - {Loc.GetString("tutorial-cybermed-step-locked")}";

            var button = new Button
            {
                Text = text,
                Disabled = !step.Available || step.Completed,
                HorizontalExpand = true,
                ToolTip = string.IsNullOrEmpty(step.Description) ? step.Name : step.Description,
            };

            if (step.Completed)
                button.Modulate = Color.Green;

            var stepId = step.StepId;
            button.OnPressed += _ => OnStepSelected?.Invoke(stepId);
            StepsList.AddChild(button);
        }
    }
}
